=== ASGyula/E24HDOWebXML/E24HDO_0930/E24HDO_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT E24HDO_kurzusfelvetel (hallgató+, kurzusok+)>
<!ATTLIST E24HDO_kurzusfelvetel tanév CDATA #REQUIRED>
<!ATTLIST E24HDO_kurzusfelvetel egyetem CDATA #REQUIRED>
<!ELEMENT hallgató (hallgato)>
<!ELEMENT hallgato (hnev, szulev, szak)>
<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ATTLIST szak evf (#PCDATA) #REQUIRED>
<!ELEMENT kurzusok (kurzus)>
<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont+, (oktato | oraado))>
<!ATTLIST kurzus id ID #REQUIRED>
<!ATTLIST kurzus jovahagyas (igen | nem) "nem" #IMPLIED>
<!ATTLIST kurzus nyelv CDATA #IMPLIED>
<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>

=== ASGyula/E24HDOWebXML/E24HDO_0930/E24HDO_kurzusfelvetel2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE E24HDO_kurzusfelvetel SYSTEM "E24HDO_kurzusfelvetel.dtd">
<E24HDO_kurzusfelvetel tanév="2026/27" egyetem="ME">

    <hallgató>
        <hallgato>
            <hnev>Héjjas Gyula</hnev>
            <szulev>2004</szulev>
            <szak evf="3">Programtervező Infromatikus</szak>
        </hallgato>
    </hallgató>

    <kurzusok>
        <kurzus id="GEIAL331-B2-01" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Webtech 1</kurzusnev>
            <kredit>5</kredit>
            <hely>
                In/101
            </hely>
            <idopont>
                szerda 12-14
            </idopont>
            <oktato>
                Dr. Bednarik László
            </oktato>
            <oraado>
                Dr. Bednarik László
            </oraado>
        </kurzus>
        <kurzus id="GEIAL32K-B2-01" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Webes adatkezelő kökrnyezetek</kurzusnev>
            <kredit>5</kredit>
            <hely>
                In/101
            </hely>
            <idopont>
                szerda 10-12
            </idopont>
            <oktato>
                Dr. Bednarik László
            </oktato>
        </kurzus>
        <kurzus id="GEMAK234-B2-01" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
            <kredit>5</kredit>
            <hely>
                E30
            </hely>
            <idopont>
                kedd 14-16
            </idopont>
            <oraado>
                Házy Attila
            </oraado>
        </kurzus>
    </kurzusok>

</E24HDO_kurzusfelvetel>
